[package]
name = "see-aug"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = { version = "0.1.8", features = ["devtools", "log"] }
# Use the same version as Freya for all of these:
dioxus = { version = "*", features = ["macro", "hooks"] }
dioxus-std = { version = "*", features = ["utils"] }
skia-safe = "*"
log = "*"
tokio = "*"

# Utils
arc-swap = "1.6.0"
boxcar = "0.2.4"
image = "0.24"


[profile.dev]
opt-level = 1