[package]
name = "see-aug-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_zip = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
