name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        lfs: true
    - name: Install deps
      run: sudo apt-get update; sudo apt-get install build-essential libssl-dev pkg-config cmake libgtk-3-dev libclang-dev
    
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ./target/
        key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.lock') }}
    
    - uses: dtolnay/rust-toolchain@nightly
      with:
        targets:
          wasm32-unknown-unknown,
          x86_64-pc-windows-gnu,
          i686-pc-windows-gnu,
          x86_64-apple-darwin,
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --workspace --verbose
